# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket         = "arengifoc-terraform-tfstate"
    dynamodb_table = "terragrunt-lock"
    encrypt        = true
    key            = "mysql/terraform.tfstate"
    region         = "us-east-1"
  }
}
